name: etexCore
version: '${project.version}'
main: me.uranusdestroyer.etexcoreplugin.etexCorePlugin
api-version: 1.20
load: STARTUP
authors: [ Kchulka ]
description: Main plugin needed for every etex plugin.
commands:
  etexcore:
    description: Main command
    aliases:
      - ecp
  stash:
    description: Stash command
  atm:
    description: Atm command